# Generated by Django 5.2.7 on 2025-10-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gravacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='gravacoes')),
                ('data', models.DateTimeField()),
                ('transcrever', models.BooleanField(default=False)),
                ('humor', models.IntegerField(default=0)),
                ('transcricao', models.TextField()),
                ('resumo', models.JSONField(blank=True, default=list)),
                ('segmentos', models.JSONField(blank=True, default=list)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.pacientes')),
            ],
        ),
    ]
